# .github\workflows\ci.yml

name: CI

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'fix/**'
      - 'hotfix/**'
      - 'release/**'
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-typecheck:
    name: Test • Type-check
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Validate branch name
        run: npx --yes validate-branch-name

      - name: Install dependencies (npm ci)
        if: ${{ hashFiles('package-lock.json') != '' }}
        run: npm ci --no-audit --no-fund
      - name: Install dependencies (npm i)
        if: ${{ hashFiles('package-lock.json') == '' }}
        run: npm i --no-audit --no-fund

      - name: Type check
        run: npx tsc -p tsconfig.json --noEmit

      - name: Unit tests (jest-expo)
        env:
          CI: true
        run: npm test -- --ci --coverage --runInBand

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
